data:extend({
  {
    type = "int-setting",
    name = "ghost-crafter-craft-count",
    setting_type = "runtime-per-player",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 1000,
    order = "a",
  },
  {
    type = "int-setting",
    name = "ghost-crafter-bonus-inventory-slots",
    setting_type = "runtime-per-player",
    default_value = 0,
    minimum_value = 0,
    maximum_value = 500,
    order = "b",
  },
  {
    type = "double-setting",
    name = "ghost-crafter-crafting-speed-modifier",
    setting_type = "runtime-per-player",
    default_value = 1.0,
    minimum_value = 1.0,
    maximum_value = 10.0,
    order = "c",
  },
  {
    type = "double-setting",
    name = "ghost-crafter-movement-speed-modifier",
    setting_type = "runtime-per-player",
    default_value = 1.0,
    minimum_value = 1.0,
    maximum_value = 5.0,
    order = "d",
  },
})
